### ISSUE TITLE
Patching xml files fails when Gapps is installed in system_ext partition

### ISSUE THREAD

**Issue by alphajoza** [gloeyisk/universal-gms-doze#10]
A number of Gapps flashable zip packages (such as Flamegapps), install Google Apps on system_ext partition and based on the code in **customize.sh** file, patching is checked only in system, product and vendor partitions. I had to manually patch mine which was located in:

/system_ext/etc/sysconfig/google.xml

**Comment by Fenyx93** [comment]
Same issue here with FlameGapps on AOSPExtended A11 with Magisk 24.3.

**Comment by Fenyx93** [comment]
@gloeyisk Please what could we do or which informations could we provide to help you fix this issue?
