### ISSUE TITLE
Not getting notifications 

### ISSUE THREAD

**Issue by 98Mba** [gloeyisk/universal-gms-doze#11]
I just installed universal gms doze, and now I'm not getting notifications from Telegram and WhatsApp

**Comment by djdeeles** [comment]
Me too any fix?

**Comment by EleoXDA** [comment]
Did you follow procedure by typing these?
> su
> cd /data/data
> find . -type f -name '*gms*' -delete

**Comment by rizkycba94** [comment]
> Did you follow procedure by typing these?
> 
> > su
> > cd /data/data
> > find . -type f -name '_gms_' -delete

how to get "gms name list"?
mine whatsapp notification delay

**Comment by EleoXDA** [comment]
> > Did you follow procedure by typing these?
> > 
> > > su
> > > cd /data/data
> > > find . -type f -name '_gms_' -delete
> 
> how to get "gms name list"?
> mine whatsapp notification delay

In the readme file at "Command-line for fix delayed incoming messages issue" part there is a command line to fix it. This should fix the issue. If not, please report back.

**Comment by kovaacicc** [comment]
Hi,
I am also facing this problem even after running the command several times. Sometimes the notifications stop working for whatsapp and snapchat and when I enter the apps only then do I get the messages.
Im on miui 13.

**Comment by gloeyisk** [comment]
> Im on miui 13.

Sometimes MIUI kills an app that closed from Recents, you need either lock it on Recents or put the app to Not Optimized battery usage in the Settings.
