### ISSUE TITLE
Does not work for Oneplus 8T Android 12

### ISSUE THREAD

**Issue by jiang-yuan** [gloeyisk/universal-gms-doze#12]
gms_v1.8.5.zip
Set this module on at masigk and reboot already.
Type 'gmsc'
shows 'Google Play services is Not Optimized'
Do I need to set up any other thing manually?

**Comment by h0wller** [comment]
Same. CrDroid 8.6 POCO X3 PRO

**Comment by gorillap** [comment]
Confirmed same on OP9 with OOS12 C.62

**Comment by gloeyisk** [comment]
Please try the latest update, working or not you can feel free to contact me.
