### ISSUE TITLE
Works on Lineage 14.1 but not on 18.1

### ISSUE THREAD

**Issue by kiai72** [gloeyisk/universal-gms-doze#13]
i tried on 2 samsung tablets: on the one with lineage 14.1 it works - but on 18.1 battery saving is still not available for play services,
The module is listed as active in magisk modules.

any advice ?
The not working tablet with 18.1 is a SM-T550. It has multiuser support - if this is relevant ?

**Comment by DymondZ** [comment]
Works fine here on my Redmi Note 10 Pro using A13 pOS, so I don't think your issue is depending on the Android version but rather on your particular ROM

**Comment by gloeyisk** [comment]
Please try the latest update, working or not you can feel free to contact me.
