### ISSUE TITLE
Clarification regarding source code and license

### ISSUE THREAD

**Issue by UnlimitedCookies** [gloeyisk/universal-gms-doze#14]
Hello there,

why is there no more source code at the current head of the master branch. All remaining scripts have been removed in 918b29a16897cf4fb5b161703e13b049e6082f90 and funnily enough, there's a GPL License protecting the freedom of a README and some Changelog.md?! Was there ever all source available?

Could somebody please clarify?

**Comment by gloeyisk** [comment]
It's returned. Closing.
