### ISSUE TITLE
Extracting module files

### ISSUE THREAD

**Issue by Lycidias93** [gloeyisk/universal-gms-doze#15]
Latest version hangs on "extracting module files"

Latest Stock Rom on pixel 6 pro

![Screenshot_20220717-125802](https://user-images.githubusercontent.com/42116872/179395100-e34099cf-14c4-43a7-b8ee-0048428cd6e5.png)

**Comment by gloeyisk** [comment]
> Latest version hangs on "extracting module files"
> 
> Latest Stock Rom on pixel 6 pro
> 
Patience, my friend.

**Comment by Lycidias93** [comment]
You were right!😄
