### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by Alex-x90** [gloeyisk/universal-gms-doze#16]
When trying to install version 1.8.5 or 1.8.6 (and possibly on older versions, although I haven't tested), I get the error "Please install Magisk v20.4+!". However, my device is on magisk v23.0 so there shouldn't be an issue here. Device is galaxy s10+ running android 11 HyperRom.

**Comment by HuskyDG** [comment]
Did you complete "Additional Setup"?

**Comment by Alex-x90** [comment]
I'm assuming you mean for magisk, and no. Last time I did it bootlooped my device so I'm not going to do it again since everything is working.

**Comment by gloeyisk** [comment]
Closing the issue, this is not related with the module.
