### ISSUE TITLE
V1.8.6 doesn't work, can't optimized

### ISSUE THREAD

**Issue by msizaky16** [gloeyisk/universal-gms-doze#17]
Newer version didn't work on my Redmi Note 10 Pro with Nusantara Rom (AOSP) using Magisk 25.2.
Work fine with v1.8.5

**Comment by eugene-reim** [comment]
Redmi K20
AncientOS A12
Magisk 25.2

Also can't optimize

**Comment by babayaga2020** [comment]
No version of gmsdoze ever worked on my poco x3 pro android 12.1 magisk latest version. never.

![Screenshot_20220724-114254_Termux](https://user-images.githubusercontent.com/76453578/180655316-3fa27960-f4a1-41a4-818b-574a04d011c9.png)

![Screenshot_20220724-113012_Configurações](https://user-images.githubusercontent.com/76453578/180655339-8c07239c-292f-439c-be72-0e7d72b3239e.png)

**Comment by babayaga2020** [comment]
Bro try make a version to poco x series please, thank you, no one version worked on my poco x3 pro, i dont know why... Android 12.1, custom ROM crdroid 8.6 actually.

**Comment by franciscomoura99** [comment]
1.8.6 isn't working on my OnePlus 7 Pro running stock OxygenOS 11.0.8 and Magisk 25.2. Like the OP, 1.8.5 is working perfectly.
By this I mean that when running "dumpsys deviceidle" or "gmsc" on 1.8.5 shows that gms is optimized while doing the same on 1.8.6 shows not optimized.

Thanks!

**Comment by tmstaedt** [comment]
> Newer version didn't work on my Redmi Note 10 Pro with Nusantara Rom (AOSP) using Magisk 25.2. Work fine with v1.8.5

Can confirm that. device: oneplus3, android 11 custom ROM

**Comment by gloeyisk** [comment]
Please try the latest update, working or not you can feel free to contact me.
