### ISSUE TITLE
multi user support

### ISSUE THREAD

**Issue by rhjdvsgsgks** [gloeyisk/universal-gms-doze#2]
```bash
pm disable com.google.android.gms/com.google.android.gms.auth.managed.admin.DeviceAdminReceiver
```
will only disable this receiver for main user. `--user x` argument is needed if trying to disable this receiver for other user. and `cmd appops` also same like this.

**Comment by rhjdvsgsgks** [comment]
fine, i did it #3

**Comment by gloeyisk** [comment]
It's done, and added now.
