### ISSUE TITLE
Delay Notification

### ISSUE THREAD

**Issue by snsnfsh** [gloeyisk/universal-gms-doze#21]
Delay Notification in Android 12.1, patch July, Google pixel 5
Like Whatsapp, ig

And can you add the auto delete 'gms' feature, like 6 hours 1 x or once a day

**Comment by AgentlReal** [comment]
How to add the auto delete 'gms'  feature? Because i always do it manually

**Comment by gloeyisk** [comment]
> Delay Notification in Android 12.1, patch July, Google pixel 5 Like Whatsapp, ig

Follow the troubleshooting once, do a reboot, and put your apps that had these issue to Not Optimized battery usage.
