### ISSUE TITLE
Still red when checking with "gmsc*

### ISSUE THREAD

**Issue by degr15** [gloeyisk/universal-gms-doze#22]
Google play services can't be optimize through battery setting. It worked before when I was still using version 1.8.6. I'm using crdroid 8.8 A12L

**Comment by lordsiomai** [comment]
Same issue here on Xiaomi lime havoc os 4.19 magisk 25.2

**Comment by kouzelnik3** [comment]
Same issue on oxygen os 12.1 latest patch

**Comment by ghost** [comment]
Same issue on latest Los 19.1 (poco x3 pro)... reverted back to v1.8.6

**Comment by Gluneklairo** [comment]
[magisk_install_log_2022-09-16T12.47.16.log](https://github.com/gloeyisk/universal-gms-doze/files/9580780/magisk_install_log_2022-09-16T12.47.16.log)
Same, and finding system xml process is low.
