### ISSUE TITLE
unable to add: /product/product

### ISSUE THREAD

**Issue by wuzuyuuu** [gloeyisk/universal-gms-doze#24]

**Comment by Gluneklairo** [comment]
https://github.com/gloeyisk/universal-gms-doze/issues/23#issuecomment-1249379218
Same issue as mine, you can view the solution in this link above.

**Comment by gloeyisk** [comment]
Please try the latest update, working or not you can feel free to contact me.

**Comment by wuzuyuuu** [comment]
It works now
