### ISSUE TITLE
Not working on Crdroid 8.9, Android 12.1

### ISSUE THREAD

**Issue by aanneion** [gloeyisk/universal-gms-doze#25]
The battery option still stays "not optimized" for the google play services app

**Comment by aanneion** [comment]
![Uploading Screenshot_20220930-122112_Termux~2.png…]()

**Comment by aanneion** [comment]
![Screenshot_20220930-122112_Termux~2](https://user-images.githubusercontent.com/78258079/193204385-1c0f9930-17a1-4b84-9336-f5c8a33e1c0f.png)

**Comment by Gluneklairo** [comment]
Read this solution
https://github.com/gloeyisk/universal-gms-doze/issues/23#issuecomment-1249379218

**Comment by gloeyisk** [comment]
Please try the latest update, working or not you can feel free to contact me.
