### ISSUE TITLE
Play Store not working 

### ISSUE THREAD

**Issue by Arpan012001** [gloeyisk/universal-gms-doze#26]
![Screenshot_20221008-020810_Google Play Store](https://user-images.githubusercontent.com/115319918/194648883-e8f56157-d7a9-4f06-90ed-b7727954e55b.png)
Google play Store is not working in my device Redmi 9T, currently I am using Pixel Extended Rom based on Android 12.

**Comment by cihaneken** [comment]
I confirm this.  Mi9 Android 10 official Miui version.  After activating the module, the play store does not work.

**Comment by gloeyisk** [comment]
Please try the latest update, working or not you can feel free to contact me.
