### ISSUE TITLE
1.8.6 working 1.8.7 not working

### ISSUE THREAD

**Issue by canakay58** [gloeyisk/universal-gms-doze#27]
I am using miui 13 EU Rom (Android 12). 1.8.6 working but 1.8.7 not working :(

**Comment by Gluneklairo** [comment]
Read this solution
https://github.com/gloeyisk/universal-gms-doze/issues/23#issuecomment-1249379218

**Comment by gloeyisk** [comment]
Please try the latest update, working or not you can feel free to contact me.
