### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by islam2hamy** [gloeyisk/universal-gms-doze#28]
Hi ,

What does this mean?

>santoni:/ $ su
santoni:/ # gmsc
/system/bin/gmsc[32]: awk: not found
Failed to write while dumping service deviceidle: Broken pipe
[1;32m Google Play services is Optimized. [0m
santoni:/ # 

Thank you

**Comment by islam2hamy** [comment]
Also , does i need to install this module ?

https://github.com/VR-25/sysconfig-patcher

Or installing your module only is enough

**Comment by gloeyisk** [comment]
> Hi ,
> 
> What does this mean?
> 
> > santoni:/ $ su
> > santoni:/ # gmsc
> > /system/bin/gmsc[32]: awk: not found
> > Failed to write while dumping service deviceidle: Broken pipe
> > [1;32m Google Play services is Optimized. [0m
> > santoni:/ #
> 
> Thank you

That mean the module is installed and working normally.

**Comment by gloeyisk** [comment]
> Or installing your module only is enough

And for this, 1 module is enough. No need others.
