### ISSUE TITLE
Google Play Games Messed Up

### ISSUE THREAD

**Issue by ghost** [gloeyisk/universal-gms-doze#29]
I have been using universal gms doze for 2 years and i never got any issues with google play games. Last week (i was using gms doze v1.8.7)  i installed a game and wanted to sync app data from google play games, when i selected the sync option, the google play overlay appeared and disappeared on the spot. After clearing data/cache of services and store, i realized something is wrong with my rom so i switched to miui based rom (Miui CSX 13.0.8)  just to see if its happening with AOSP based rom or not and doze didn't worked on CSX too.

Current Stats
Device : Poco X3 Pro
OS : LineageOS 19.1 Official

Whenever i select Optimized state of "Google Play Services" in battery usage, the google play games doesn't work anymore.

**Comment by ghost** [comment]
So after uninstalling universal gms doze (on Unrestricted). i solved my problem and google play games working fine without universal gms doze.

**Comment by gamersfan** [comment]
I fix it afrer deleting/updating google service and installing again google play games.
Also i add file 123.sh at data/adb/service.d (magisk autostart dir)
Write here:
sleep 20
su -c pm enable com.google.android.gms/.chimera.GmsIntentOperationService

This will start google service IntentOperation while system start, and module will turn it off after 100 seconds.
It help with notification, so maybe help with play games too.
