### ISSUE TITLE
Location not working after uninstalling 

### ISSUE THREAD

**Issue by brahm23** [gloeyisk/universal-gms-doze#30]
I flashed this module and then it didn't affect much so I uninstalled it. After uninstalling it my location sharing of phone got turned off and now I'm not able to turn it on. Because of this issue, my apps like uber, ola, rapido or any other app which requires live location isn't working. It just crashes and gives the error -
(Name of app) keeps stopping.

**Comment by gloeyisk** [comment]
> I flashed this module and then it didn't affect much so I uninstalled it. After uninstalling it my location sharing of phone got turned off and now I'm not able to turn it on. Because of this issue, my apps like uber, ola, rapido or any other app which requires live location isn't working. It just crashes and gives the error - (Name of app) keeps stopping.

Confirm me with these build.
[gms_v1.8.8-locfix.zip](https://github.com/gloeyisk/universal-gms-doze/files/10212309/gms_v1.8.8-locfix.zip)

**Comment by brahm23** [comment]
> > I flashed this module and then it didn't affect much so I uninstalled it. After uninstalling it my location sharing of phone got turned off and now I'm not able to turn it on. Because of this issue, my apps like uber, ola, rapido or any other app which requires live location isn't working. It just crashes and gives the error - (Name of app) keeps stopping.
> 
> Confirm me with these build. [gms_v1.8.8-locfix.zip](https://github.com/gloeyisk/universal-gms-doze/files/10212309/gms_v1.8.8-locfix.zip)

It fixed the issue THANK YOU VERY MUCH❤️
