### ISSUE TITLE
⚠️ WARNING - BEWARE INSTALLING THIS! ⚠️

### ISSUE THREAD

**Issue by Samg381** [gloeyisk/universal-gms-doze#34]
### FYI, this module completely broke up my notifications on Android 13 (Pixel 4XL)​
Even worse, I didn't realize I wasn't getting notifications until I missed several important google reminders.
I had to uninstall 'Google' and 'Google Play Services' with De-bloater, reinstall it, clear cache, reboot etc. to fix it.
This module should be marked as incompatible with A13.

**Comment by gloeyisk** [comment]
> 'Google' and 'Google Play Services' with De-bloater, reinstall it

A little bit out of topic but, where you can get those De-bloater? Need to check it.

**Comment by CleanerThanRotom-W** [comment]
> > 'Google' and 'Google Play Services' with De-bloater, reinstall it
> 
> A little bit out of topic but, where you can get those De-bloater? Need to check it.

[Here](https://github.com/sunilpaulmathew/De-Bloater)

**Comment by davidthefrikr** [comment]
Can confirm here on Android 13 (Xperia 1 IV XQ-CT72) as well, simply reinstalling Google and Google Play Services with the de-bloater fixed the issue for me

**Comment by fillwithjoy1** [comment]
Is this an issue to this day?

**Comment by Samg381** [comment]
Yes it is. This is abandonware that will completely break your android install. Do not use it.
