### ISSUE TITLE
Any plans to add to androidacy?

### ISSUE THREAD

**Issue by ghost** [gloeyisk/universal-gms-doze#38]
[androidacy.com/magisk-modules-repository/](https://www.androidacy.com/magisk-modules-repository/)

**Comment by gloeyisk** [comment]
> [androidacy.com/magisk-modules-repository/](https://www.androidacy.com/magisk-modules-repository/)

No, for the moment.

**Comment by ghost** [comment]
Any reasons why? My guess is privacy and their adriddenfilled sh*tsite, excuse my language.

**Comment by gloeyisk** [comment]
> Any reasons why? My guess is privacy and their adriddenfilled sh*tsite, excuse my language.

Simply just watch these repo and set to Custom (Releases), so that you'll be notified when a new update is released.
