### ISSUE TITLE
Wear OS Watches

### ISSUE THREAD

**Issue by jumpingbrowntrout** [gloeyisk/universal-gms-doze#4]
Has anyone had any success with using Universal GMS Doze on a watch with Wear OS.
I have it installed on mine and have done for a while. But I love at my battery stats and 'Google Play Services' is always at the top with approximately 16% battery usage. My watch has Android 8 as OS.

I don't really understand how doze works on android watches but I would of thought it was all similar.

Keen to hear if anyone else has this working?

**Comment by gloeyisk** [comment]
Make sure to test the new build, thanks!
