### ISSUE TITLE
ROOT=?

### ISSUE THREAD

**Issue by JumbomanXDA** [gloeyisk/universal-gms-doze#40]
how you are getting value of "ROOT" variable in recent version

**Comment by gloeyisk** [comment]
It's now fixed.

**Comment by JumbomanXDA** [comment]
I am still not sure about how you are getting value of ROOT variable?

**Comment by gloeyisk** [comment]
Sending a PR will greatly appreciated!

**Comment by JumbomanXDA** [comment]
Just refer your own modules 3 version back.
