### ISSUE TITLE
How to properly uninstall? 

### ISSUE THREAD

**Issue by privacyguy123** [gloeyisk/universal-gms-doze#42]
I can still see Optimized not greyed out on GMS even after module removal ...

**Comment by Memory2314** [comment]
Need to change the file

**Comment by Memory2314** [comment]
This version can be uninstalled cleanly.
https://github.com/Memory2314/universal-gms-doze-fix

**Comment by nihal697** [comment]
> This version can be uninstalled cleanly. https://github.com/Memory2314/universal-gms-doze-fix

can you make a pull request for this module too?

**Comment by Memory2314** [comment]
> > This version can be uninstalled cleanly. https://github.com/Memory2314/universal-gms-doze-fix
> 
> can you make a pull request for this module too?

Let me try.

**Comment by nihal697** [comment]
> > > This version can be uninstalled cleanly. https://github.com/Memory2314/universal-gms-doze-fix
> > 
> > 
> > can you make a pull request for this module too?
> 
> Let me try.

the original reply is lit 😂

**Comment by gloeyisk** [comment]
Fixed. Please try the new version.
