### ISSUE TITLE
Suggestions for extra features

### ISSUE THREAD

**Issue by ogo16** [gloeyisk/universal-gms-doze#43]
Can you add a feature to enable users to add other system or user apps other than google play services? My phone's OEM whitelisted Facebook and Messenger from battery restrictions and I would like them to be removed from the whitelist as well using the same mechanism this module utilizes.

**Comment by fillwithjoy1** [comment]
heres a solution until gloeyisk comments about this idea

1. Get Shizuku
2. Install App Ops
3. Go to Facebook/Messenger and scroll down to the bottom
4. Set "Run in background" to "Strict Restriction"
hopefully that will deal with that issue for the time being
(p.s. facebook can abuse fcm push, try Hail from F-Droid if it doesn't go away and set working mode to Shizuku - Disable)
