### ISSUE TITLE
Can't run youtube 

### ISSUE THREAD

**Issue by anurag565** [gloeyisk/universal-gms-doze#44]
In samsung device, there's a deep sleep option. If u put google play services in there, youtube wont work. It kind of disables google play services. And yes, this is happening for months. I tried reinstalling gms doze but no change.

**Comment by fillwithjoy1** [comment]
> In samsung device, there's a deep sleep option. If u put google play services in there, youtube wont work. It kind of disables google play services. And yes, this is happening for months. I tried reinstalling gms doze but no change.

Thats.... perfectly normal. YouTube needs to call GMS's APIs to retrieve account info, so deep sleeping gms is a surefire way to kill it. Oh and, whatsapp calls will likely be missed and delayed notifications from apps by doing that as well. But hey, all for optimising power right?

**Comment by anurag565** [comment]
Yup buddy. Its great. Just in new One UI 6.0, magisk app wont open so i cant install any modules. Just saying, not your problem.

**Comment by fillwithjoy1** [comment]
> Yup buddy. Its great. Just in new One UI 6.0, magisk app wont open so i cant install any modules. Just saying, not your problem.

uh-oh, is it crashing completely?

**Comment by anurag565** [comment]
Not crashing, its just stuck on home screen. But i can still give root permissions to all apps. And yes, i tried installing with Androidacy magisk module manager but it didn't work.
![Screenshot_20240321_215731](https://github.com/gloeyisk/universal-gms-doze/assets/143786347/fa92e225-d476-49ed-ad78-c7451495371e)

**Comment by anurag565** [comment]
Its not only with my device, someone with One UI 6.0 complained in magisk issue section on github. I tried too but couldn't because i dont know how to take logs.

**Comment by fillwithjoy1** [comment]
Few things you can do:
1. Clear data of Magisk app and see if that fixes it

OR

Re-install Magisk clean (without re-flashing your boot image)

You could try and cleanly re-install the Magisk app, and the modules as well. (this doesn't rely on you to re-flash your boot image)
You'll need a file explorer that can see root (see [Material File Manager](https://github.com/zhanghai/MaterialFiles)) 
Go to /data/adb/modules and you can A. Delete all folders, or B. Copy them somewhere else (and be sure to delete all the files in the folder.

Uninstall the magisk app and then reboot. Your root apps may break, this is **normal**

Install the latest magisk app. If magisk is now working, then go to /data/adb/modules with a root file explorer and restore all your module files (if you decided to copy your modules to somewhere else)

**Comment by anurag565** [comment]
Already did all of that.

**Comment by anurag565** [comment]
Already did all of that, just wanted to know how to take logs of magisk and give it to their developers. Tell me please. And as I told you, this isn't just my problem, nearly all one ui 6.0 users facing this issue.

**Comment by fillwithjoy1** [comment]
adb logcat, search it up.
