### ISSUE TITLE
can't optimize gms

### ISSUE THREAD

**Issue by 7228061** [gloeyisk/universal-gms-doze#46]
I have already installed the last version of gms doze, why gms battery optimization still unavailable? 
![Screenshot_20231030-081033](https://github.com/gloeyisk/universal-gms-doze/assets/149318006/16ed6735-bd8a-4cb5-aca0-ec1d83eae931)

**Comment by gloeyisk** [comment]
> I have already installed the last version of gms doze, why gms battery optimization still unavailable?

https://github.com/gloeyisk/universal-gms-doze/issues/49#issuecomment-1838034325

**Comment by fillwithjoy1** [comment]
close issue?
