### ISSUE TITLE
Restarting the device will cause the Google Play service to change from "Optimized" to the default "Unrestricted" (and cannot be changed)

### ISSUE THREAD

**Issue by QINYUUi** [gloeyisk/universal-gms-doze#49]
Device: Motorola Edge 20(android 13)

Google Play service "Optimized" expected behavior works normally after installing Universal GMS Doze 1.9.1

But when I shut down or restart the phone, it changes to the default "Unrestricted"

Ps: It only takes effect the first time after installation...

After installation Optimized works fine[*1]
![Screenshot_20231203-113051](https://github.com/gloeyisk/universal-gms-doze/assets/151892850/39f1147f-73c6-469b-b02f-9be08e33924d)
![Screenshot_20231203-113150](https://github.com/gloeyisk/universal-gms-doze/assets/151892850/81820c54-6270-43e9-a168-e8397ac963ff)

This is a problem that occurs after restarting (video recording screen)[*2]
https://github.com/gloeyisk/universal-gms-doze/assets/151892850/a0d81636-680f-4639-be7a-042a2f4ca919

**Comment by gloeyisk** [comment]
Flash the module once again, reboot your device, and when your ROM is booted, don't open your lock screen for about 2 minutes (just to make sure the script is running correctly).

**Comment by harphere** [comment]
> Flash the module once again, reboot your device, and when your ROM is booted, don't open your lock screen for about 2 minutes (just to make sure the script is running correctly).

This worked for me. Thanks!

**Comment by chaoscreater** [comment]
If anyone uses MacroDroid or Tasker, you can just set a task to automatically run the shell script on phone boot up. The script is located at:
/data/adb/modules/universal-gms-doze/service.sh

**Comment by NCLnclNCL** [comment]
> If anyone uses MacroDroid or Tasker, you can just set a task to automatically run a shell script on phone boot up.
> 
> You can find the contents of the shell script located here: /data/adb/modules/universal-gms-doze/service.sh
> 
> In the script, it uses sleep 100, which basically waits 100 seconds for the phone to finish booting up before it runs the rest of the script. You can ignore this. Just copy the stuff after that point into your MacroDroid/Tasker script.

U only edit time, dont need use taker
