### ISSUE TITLE
Degrading GMS doze performance over time?

### ISSUE THREAD

**Issue by vintagepc** [gloeyisk/universal-gms-doze#5]
This is a bit of a weird issue I am running into. Previously, GMS doze worked wonderfully, and I would get 4-5 days of battery life out of my phone. 

However, as of some time ago it seems like it is no longer working reliably. Battery life went back to the above after doing a fresh install of GMS doze (was using an outdated XDA version), but over the course of a few weeks I am back to only getting about 2 days out of a charge, with Play services again using 33% or more of the battery according to the system battery manager. 

Everything checks out according to troubleshooting in the README, but I do notice that if I check the optimization settings for Play Services, it says "Not optimized" and cannot be changed (setting immediately reverts back to "Not optimized"). I could be wrong but am almost positive this said "Optimizing" when first installed and it was working.

Phone is a Razer Phone 2, with Android 9. Is there a log or some info I can provide to help troubleshoot? It's a shame because this is a great tool for dealing with unnecessary bloat in Play Services!

**Comment by vintagepc** [comment]
I think I may have found the issue; Play services had permissions to modify system settings and was overriding the effects of GMS doze. 

Revoking those permissions allows it to be optimized again and battery life seems to be back to where it should be :+1:

**Comment by gloeyisk** [comment]
> I think I may have found the issue; Play services had permissions to modify system settings and was overriding the effects of GMS doze.
> 
> Revoking those permissions allows it to be optimized again and battery life seems to be back to where it should be

I need to know what permissions you've to revoke, I also need to check it first whether it is safe or not.

**Comment by vintagepc** [comment]
Apps & Notifications -> All Apps -> Google Play Services -> Advanced -> Modify System Settings to "Not allowed".   That was the only thing I had to change in order to "fix" the issue of the process refusing to be optimized by the battery manager.  (Android 9) 

After this change GMS also no longer showed up as hogging significant battery usage in the battery stats.

**Comment by gloeyisk** [comment]
It's done now, you don't have to manually disable 'Modify system settings' for Play services.
