### ISSUE TITLE
Please tell me, will this module affect fcm push?

### ISSUE THREAD

**Issue by Chuhe2333** [gloeyisk/universal-gms-doze#53]
Please tell me, will this module affect fcm push?

**Comment by fillwithjoy1** [comment]
Depends, if you set the background policy to restricted, you are going to suffer fcm push losses. Also when the phone is dozing, if the background policy is NOT set to unrestricted, then GMS is shut down during doze which means no notifications at all if you dont touch your phone. It all depends on your needs on FCM push, and you can always look into restricting other apps as an alternative

**Comment by Chuhe2333** [comment]
Thank you for clearing up the confusion.

**Comment by Chuhe2399** [comment]
Thank you for clearing up the confusion.

**Comment by Chuhe2399** [comment]
Thank you for clearing up the confusion.
