### ISSUE TITLE
I think LMK or sth goes aggressive after I install this module

### ISSUE THREAD

**Issue by TheWrathRF** [gloeyisk/universal-gms-doze#54]
After installing this via Magisk most of my apps begin to turn off itself in the background. For instance, Adguard and YouTube suddenly kills itself randomly. ( I am curious how this module can kill other apps)  There are no restrictions or something and after I uninstall the module everything turns back to normal. By the way, I am using Crdroid 10.2. Zram and SWAP are active. There are no RAM limitations which causes aggressive memory killing progressions. Phone model: Xiaomi Redmi Note 8

**Comment by CharlieCoops7** [comment]
Same issue for me on android 14
