### ISSUE TITLE
Stop Google Play Services auto-update?

### ISSUE THREAD

**Issue by chaoscreater** [gloeyisk/universal-gms-doze#56]
Hi,

I got this module working on my Redmi K60 running MIUI 14, Android 13. It works great, but the problem is that every now and then, Google Play Services will automatically update and I'm guessing the universal-gms-doze module will stop working and needs to be updated again. I'd rather just stay on an older Google Play Services version and update it manually myself after 6 months or 1 year. I know how to block normal apps from auto-updating, but I don't have any working methods to do this for Google Play Services.

Does anyone have any ideas?

**Comment by SzBenedek2006** [comment]
You can turn it off here:

![Screenshot_20240522_095539_Google Play services.png](https://github.com/gloeyisk/universal-gms-doze/assets/95222597/3bfcda21-cb77-41c2-a4ca-605cd7b6a3ff)

![Screenshot_20240522_095517_Google Play Store.png](https://github.com/gloeyisk/universal-gms-doze/assets/95222597/eb740f4b-901b-4bf4-8497-27aabe40da43)

**Comment by chaoscreater** [comment]
> You can turn it off here:
> 
> ![Screenshot_20240522_095539_Google Play services.png](https://private-user-images.githubusercontent.com/95222597/332710646-3bfcda21-cb77-41c2-a4ca-605cd7b6a3ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjcwNzQsIm5iZiI6MTcxNjM2Njc3NCwicGF0aCI6Ii85NTIyMjU5Ny8zMzI3MTA2NDYtM2JmY2RhMjEtY2I3Ny00MWMyLWE0Y2EtNjA1Y2Q3YjZhM2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA4MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OGYxYzNkOTYwZTUwZDAwOWI1OGU5MGNmZTcxZTAxM2NiYmNlMzFkZTcxNTEwNmMwZTAxOWM4NTM2Yjc5NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zbumFkTRkos5-cwCk1f6ocb3trZq-79MMGQj3kHWnRA)
> 
> ![Screenshot_20240522_095517_Google Play Store.png](https://private-user-images.githubusercontent.com/95222597/332710645-eb740f4b-901b-4bf4-8497-27aabe40da43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjcwNzQsIm5iZiI6MTcxNjM2Njc3NCwicGF0aCI6Ii85NTIyMjU5Ny8zMzI3MTA2NDUtZWI3NDBmNGItOTAxYi00YmY0LTg0OTctMjdhYWJlNDBkYTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA4MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzAyZjU2NmE5YWYwNjAzMjE3YTRhYTZhNzRkNjYyMWU1ZTliYWEwYmYzYjBjMDkzZjA5NmJiZGZmNmE3NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PdbwPhCoaRlWeXJdnrAx1QuC4geDRR7j8A8Woj0N9Z8)

Hmm interesting, I don't see that on my phone and have never seen that before, regardless if I'm on a stock ROM or custom ROM. What phone and what ROM are you using?

**Comment by SzBenedek2006** [comment]
Samsung, OneUI

The second screen is part of play store, this activity:
![Screenshot_20240522_105540_Root Activity Launcher.png](https://github.com/gloeyisk/universal-gms-doze/assets/95222597/093ae442-66f2-403c-b9d4-0e2dbbf93907)

You can try to launch it using root activity launcher or ADB commands.

**Comment by chaoscreater** [comment]
> Samsung, OneUI
> 
> The second screen is part of play store, this activity: ![Screenshot_20240522_105540_Root Activity Launcher.png](https://private-user-images.githubusercontent.com/95222597/332730747-093ae442-66f2-403c-b9d4-0e2dbbf93907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjU2NjUsIm5iZiI6MTcyMzcyNTM2NSwicGF0aCI6Ii85NTIyMjU5Ny8zMzI3MzA3NDctMDkzYWU0NDItNjZmMi00MDNjLWI5ZDQtMGUyZGJiZjkzOTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NWExOTEzZmI0Y2MwZWVmMTlmNzliMjk2ZTQ2NTM2ODg4YjU0MzBkNzZjZTM3ZDE4YjM4YTJlNWJmNTRkYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oG7W96FWA1i6AXjUlUsIbh6YC8-LPN2GDBJtqZn0rcs)
> 
> You can try to launch it using root activity launcher or ADB commands.

Sorry, missed your reply. I've disabled it months ago, same as what is shown in your screenshot. My Google Play Services is still updated. I think what you've shown is for Google Play Store itself, not Google Play Services.
