### ISSUE TITLE
Can KernelSu be run on?

### ISSUE THREAD

**Issue by Cheng-MaoMao** [gloeyisk/universal-gms-doze#57]
I am using KernelSU to become root on Android 14. Is this module working properly?

**Comment by gloeyisk** [comment]
> I am using KernelSU to become root on Android 14. Is this module working properly?

It does supported and properly working.
Btw I've a plan to release a new one whenever the Android 15 is released.

**Comment by Cheng-MaoMao** [comment]
> > I am using KernelSU to become root on Android 14. Is this module working properly?
> 
> It does supported and properly working. Btw I've a plan to release a new one whenever the Android 15 is released.

Waiting for your good news.(∠・ω< )⌒★
