### ISSUE TITLE
Youtube revanced 

### ISSUE THREAD

**Issue by ghost** [gloeyisk/universal-gms-doze#58]
![Screenshot_20240907_122259_YouTube](https://github.com/user-attachments/assets/74fc9b98-731b-47a4-8254-890905baa84c)

**Comment by gloeyisk** [comment]
> ![Screenshot_20240907_122259_YouTube](https://private-user-images.githubusercontent.com/176424097/365398493-74fc9b98-731b-47a4-8254-890905baa84c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDA4MzcsIm5iZiI6MTcyNTc0MDUzNywicGF0aCI6Ii8xNzY0MjQwOTcvMzY1Mzk4NDkzLTc0ZmM5Yjk4LTczMWItNDdhNC04MjU0LTg5MDkwNWJhYTg0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QyMDIyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzNjOTJmZTI0YTExYjJhMDQyM2M1MzgxOTI3MGMzNWE5MjU1Y2ZkNDA0N2Y3NWI5ZGNkY2Y4NmM3ZDcyNDdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.90LrAAb2rad4kT9Upvf_dPjwCMU3EMnByALpmM9Z5x8)

This is not related to my module.

**Comment by ghost** [comment]
Is backup load , i don't what have do
![Screenshot_20240907_203748_YouTube](https://github.com/user-attachments/assets/5ed205a4-8b3f-4738-8890-11e87809beec)
