### ISSUE TITLE
Gms re-enable nearby service on boot

### ISSUE THREAD

**Issue by xDoge26** [gloeyisk/universal-gms-doze#6]
Please remove "pm disable find my device..." line
its cause gms re-enable nearby service on boot
 
instead use pm disable persistent ,intent service to stop gms running in background

My device after deleting pm disable find my device :
![Screenshot_20211022-211614_Cài_đặt](https://user-images.githubusercontent.com/92904701/138469709-cc60b567-5ac3-4db0-939f-c83133535ff1.png)

**Comment by varunpilankar** [comment]
What do you mean by instead use pm disable persistent ,intent service to stop gms running in background?

Can you elaborate on this?
