### ISSUE TITLE
Google Play Services is not optimized.

### ISSUE THREAD

**Issue by XAlboX** [gloeyisk/universal-gms-doze#60]
After updating the module to the latest version it doesn't work anymore (I'm using Android 14 and KSU 11872, KSU Manager version: 11928)
![Screenshot_20241201-143527_Termux.png](https://github.com/user-attachments/assets/1768cb6b-6fe5-49ff-9752-19251ed1cb11)

**Comment by gloeyisk** [comment]
> After updating the module to the latest version it doesn't work anymore (I'm using Android 14 and KSU 11872, KSU Manager version: 11928)

Try [this](https://github.com/gloeyisk/universal-gms-doze/issues/59#issuecomment-2506330228) or [this](https://github.com/gloeyisk/universal-gms-doze/issues/59#issuecomment-2506351322).

**Comment by XAlboX** [comment]
> > After updating the module to the latest version it doesn't work anymore (I'm using Android 14 and KSU 11872, KSU Manager version: 11928)
> 
> Try [this](https://github.com/gloeyisk/universal-gms-doze/issues/59#issuecomment-2506330228) or [this](https://github.com/gloeyisk/universal-gms-doze/issues/59#issuecomment-2506351322).
> 

Clean installation solved the problem, thanks 🥰
