### ISSUE TITLE
I am not receiving notifications from telegram

### ISSUE THREAD

**Issue by Xusysy** [gloeyisk/universal-gms-doze#61]
What should I do to receive messages from telegram?
Android 15, Pixel 7 Pro

**Comment by gloeyisk** [comment]
> What should I do to receive messages from telegram? Android 15, Pixel 7 Pro

First run these:
```
> su
> cd /data/data
> find . -type f -name '*gms*' -delete
```

After that, select the app (in your case is Telegram) to Not Optimized battery usage in Settings then reboot your phone.
