### ISSUE TITLE
Not working on Android 12 Poco X3 Pro crDroid

### ISSUE THREAD

**Issue by josesilveiraa** [gloeyisk/universal-gms-doze#7]
I've just installed this module but I can't optimize Google play services in the settings with latest update and magisk 24.1

**Comment by gloeyisk** [comment]
> I've just installed this module but I can't optimize Google play services in the settings with latest update and magisk 24.1

How did you check the GMS is optimized or not? Also, did you wait ±100 seconds after your phone booted up without opening your lockscreen?

**Comment by josesilveiraa** [comment]
> > I've just installed this module but I can't optimize Google play services in the settings with latest update and magisk 24.1
> 
> How did you check the GMS is optimized or not? Also, did you wait ±100 seconds after your phone booted up without opening your lockscreen?

I checked it in the Google Play Services battery services, and I didn't wait that time

**Comment by alexeei** [comment]
Poco F2 Pro A12 Syberia ROM same situation, after gmsc write Google Play service NOT optimized, try wait 120 sec without log in, same situation. Gapps-latest FlameGapps

**Comment by bbivan** [comment]
Is working fine with the latest version, now using A12 ROM
![Screenshot_20220309-162950_Settings](https://user-images.githubusercontent.com/5362757/157402708-f49f6c9d-0c09-40ee-b207-92b52a53a1c7.png)

**Comment by josesilveiraa** [comment]
> Is working fine with the latest version, now using A12 ROM
> ![Screenshot_20220309-162950_Settings](https://user-images.githubusercontent.com/5362757/157402708-f49f6c9d-0c09-40ee-b207-92b52a53a1c7.png)
> 

![Screenshot_20220309-212801_Termux.png](https://user-images.githubusercontent.com/85128820/157562731-db1dc32a-ee68-4a9e-9fa5-1bdc23687b88.png)

**Comment by josesilveiraa** [comment]
please fix it

**Comment by bbivan** [comment]
I think the latest version is working, as follow the trouble shooting instructions. Thanks 
![Screenshot_20220323-140120_Settings](https://user-images.githubusercontent.com/5362757/159634224-e246b448-ac38-44af-bee0-2a460f2f229f.png)
![Screenshot_20220323-140056_Termux](https://user-images.githubusercontent.com/5362757/159634227-11743101-3934-40e6-96f8-e139853af78b.png)

**Comment by babayaga2020** [comment]
![Screenshot_20220701-131135_Configurações](https://user-images.githubusercontent.com/76453578/176940148-8017b9c8-02c9-4af5-a3e7-68b38447be23.png)

not working on poco x3 pro crdroid 8.6 magisk 25.1 !!!

**Comment by IGProd** [comment]
> ![Screenshot_20220701-131135_Configurações](https://user-images.githubusercontent.com/76453578/176940148-8017b9c8-02c9-4af5-a3e7-68b38447be23.png)
> 
> not working on poco x3 pro crdroid 8.6 magisk 25.1 !!!

Hi,
I just realized that gmsc turns green only when my phone is disconnected from the internet; when I turn it back on (mobile network/wifi), it turns red.
No google gms when conection is disabled
Whitelist (except idle) system apps:
com.android.providers.calendar
com.android.providers.downloads
com.qualcomm.qti.telephonyservice
com.android.mms
com.qualcomm.qcrilmsgtunnel
com.qti.xdivert
com.android.cellbroadcastreceiver
com.android.proxyhandler
com.qualcomm.qti.ims
com.qualcomm.location
com.android.shell
com.google.android.cellbroadcastreceiver
com.qualcomm.atfwd
com.android.providers.contacts
google gms existe when conection is turn on
Whitelist (except idle) system apps:
com.android.providers.calendar
com.android.providers.downloads
com.qualcomm.qti.telephonyservice
com.android.vending
com.android.mms
com.qualcomm.qcrilmsgtunnel
com.qti.xdivert
com.android.cellbroadcastreceiver
com.google.android.gms
com.android.proxyhandler
com.qualcomm.qti.ims
com.qualcomm.location
com.android.shell
com.google.android.cellbroadcastreceiver
com.qualcomm.atfwd
com.android.providers.contacts

**Comment by gloeyisk** [comment]
Please try the latest update, working or not you can feel free to contact me.
